In [1]:
from JumpGP_code_py.cov.covSum import covSum
from JumpGP_code_py.cov.covSEard import covSEard
from JumpGP_code_py.cov.covNoise import covNoise
from JumpGP_code_py.lik.loglikelihood import loglikelihood
import numpy as np
from scipy.optimize import minimize
from JumpGP_code_py.local_linearfit import local_linearfit
from JumpGP_code_py.calculate_gx import calculate_gx
from JumpGP_code_py.maximize_PD import maximize_PD
from JumpGP_code_py.JumpGP_LD import JumpGP_LD
from JumpGP_code_py.simulate_case import simulate_case

import matplotlib.pyplot as plt
from sklearn.neighbors import NearestNeighbors
from skimage import measure

import numpy as np
from scipy.optimize import minimize
from scipy.linalg import cholesky
from scipy.stats import norm

from JumpGP_code_py.lik.loglikelihood import loglikelihood
from JumpGP_code_py.calculate_gx import calculate_gx
from JumpGP_code_py.cov.covSum import covSum
from JumpGP_code_py.cov.covSEard import covSEard
from JumpGP_code_py.cov.covNoise import covNoise
from JumpGP_code_py.lik.loglikelihood import loglikelihood

from ActiveJGP import ActiveJGP

import importlib

In [2]:
output = False

In [3]:
n = 100  # 行数
D = 5  # 列数
n_test = 20

x = np.random.randn(n, D)  # 生成 n x D 的随机矩阵
x0 = np.random.randn(n_test, D)

# 随机生成 Target Outputs (y)
y = np.random.randn(n, 1)  # 生成 n 行 1 列的随机列向量

# 随机生成 logtheta
logtheta = np.random.randn(D+2)  # 生成 D+1 维的随机向量
loglike = loglikelihood(logtheta, covSum, [covSEard, covNoise], x, y)
print(f"***loglike:{loglike}")

# 转换为 MATLAB 赋值语句
x_matlab = '\n'.join([' '.join(map(str, row)) for row in x])
y_matlab = '\n'.join(map(str, y.flatten()))
x_test_matlab = '\n'.join([' '.join(map(str, row)) for row in x0])
logtheta_matlab = ';\n'.join(map(str, logtheta))

if output is True:
    print("MATLAB 赋值语句：")
    print(f"x = [{x_matlab}];")
    print(f"y = [{y_matlab}];")
    print(f"x0 = [{x_test_matlab}];")
    print(f"logtheta = [{logtheta_matlab}];")
    print(f"loglike = loglikelihood(logtheta, cv,x,y);")


***loglike:316.2454265693302


In [33]:
def print_matlab(x, y, x0):
    x_matlab = '\n'.join([' '.join(map(str, row)) for row in x])
    y_matlab = '\n'.join(map(str, y.flatten()))
    x_test_matlab = '\n'.join([' '.join(map(str, row)) for row in x0])
    # logtheta_matlab = ';\n'.join(map(str, logtheta))

    print("MATLAB 赋值语句：")
    print(f"x = [{x_matlab}];")
    print(f"y = [{y_matlab}];")
    print(f"xt = [{x_test_matlab}];")
    # print(f"logtheta = [{logtheta_matlab}];")
    # print(f"loglike = loglikelihood(logtheta, cv,x,y);")

In [4]:
methods = ['MIN_IMSPE', 'MIN_ALC', 'MAX_MSPE', 'MAX_VAR', 'GP_ALC', 'JGP_LHD', 'GP_LHD']

In [5]:
k = 0

In [6]:
import ActiveJGP
importlib.reload(ActiveJGP)
from ActiveJGP import ActiveJGP

In [7]:
mode = methods[k]
xt = x0
xt_next, criteria, bias2_changes, var_changes, pred, pred_xt, pred_var, pred_bias = ActiveJGP(x, y, xt, mode)

[[47 12 81 88  3 83 41 58 66 61 64 23 92 55 33]
 [68  1 50 62 18 34 82  2 30 48 85  4 89 94 74]
 [48 82 92 18 77 15 41 65 68  1 61 47  8  2 21]
 [20 11 52 19 44 57  0 26 72 89 41 78  3 79 98]
 [61 23 74 44  1 83 85 65 48 68  5 90 87 62 38]
 [ 7 63 11 25 26 27 57 76 35 52 78 14 65 91 20]
 [19 89 54 82  0 20 18 41 21 97 72 15 52 51 59]
 [86 15  2 24  6 77 54 18 21 30 82 35 22 73 95]
 [66 64  8 12 47 17 39 55 41  9 88 92 81 80 28]
 [ 6 46 76 29 17 59 86 84 15 27 21 80 54 97 53]
 [80 39 27 28 17 22 76 84 92 15 66 21 53 64 59]
 [30 14  4 99 16 86 35 53 94 96 13 25  6  9 10]
 [89 26 35 19 54 78 20 99 51  0 18 25 82 24 97]
 [77 48 22 87  5 65  1 61 80 86 38 90 42 68 63]
 [53 17  9 64 91 96 39 60 29 76 21 16 37 35 46]
 [16 30  4 35 96 99  9 53 14 13 86 60 89 91 17]
 [33  0 72 19 52 57 44 20 41 81 78 93 11 79  3]
 [48 56 61 77 90 12 22 55 87  9 74  1 65 68 73]
 [73  2  8 86  6 77 68 48 30 15 82 17 16 18 92]
 [40 54 51 19 97 20 25 24 59 95 21 89 26 52  0]]
now m is 0, the prediction value is 0.9

In [8]:
xt_next, criteria, bias2_changes, var_changes, pred, pred_xt, pred_var, pred_bias

(array([-0.32908324,  2.37046612,  0.37083695, -1.3170471 , -0.7889676 ]),
 array([ 0.01207091, -0.07331481, -0.34235791,  0.19709524,  0.1739356 ,
         0.85312502, -0.13581187, -0.86943404,  0.06684922,  0.05752756,
        -0.67022782,  0.12472552, -0.20791679,  0.00536433, -1.56955422,
        -0.44691627,  0.72026908,  0.40219094, -0.46316237,  0.52639229]),
 array([-0.01078984, -0.30440391, -0.6013274 ,  0.        ,  0.        ,
         0.09414486, -0.39571008,  0.        ,  0.57234134,  0.        ,
         0.09786856, -0.02558815,  0.        ,  0.09420012, -0.58000962,
        -0.46815366, -0.51341942, -0.35000055,  0.        ,  0.        ]),
 array([ 0.02286075,  0.2310891 ,  0.2589695 ,  0.19709524,  0.1739356 ,
         0.75898016,  0.25989821, -0.86943404, -0.50549212,  0.05752756,
        -0.76809637,  0.15031367, -0.20791679, -0.08883579, -0.98954461,
         0.02123739,  1.23368849,  0.7521915 , -0.46316237,  0.52639229]),
 array([ 9.39264030e-01, -2.53393733e-03, -

In [26]:
args = []
N, D = x.shape
y = y.reshape(-1,1)
if y.shape[0] != N:
    raise ValueError("Row sizes of x and y should be the same!")
if xt.shape[1] != D:
    raise ValueError("Column size of x should match column size of xt!")

# Handling optional arguments
k = args[1] if len(args) > 1 else min(15, round(N * 0.2))

M = xt.shape[0]
bias2_changes = np.zeros(M)
var_changes = np.zeros(M)
pred = np.zeros(M)
pred_var = np.zeros(M)
pred_bias = np.zeros(M)
bias2 = np.zeros(M)
var = np.zeros(M)

# Nearest neighbors
nbrs = NearestNeighbors(n_neighbors=k).fit(x)
idx = nbrs.kneighbors(xt, return_distance=False)
print(idx)

models = [None] * M

[[70 62  1 10 40 15 60 82 12 90 47 89 98  8  3]
 [40 82 89  8 15 10 13  3 59 66 23 72 67 78 94]
 [86 55 20 52  3 13 51 92 78 19  8 82 85 53 72]
 [75 39 41 97 25 83 57 85 80 94 46 89 82 33 69]
 [62 12 90 10 15 70 71 98 96 32 31 40 64 94 89]
 [93 73 67 78 42 96 65 10 16 34 89 36 82 66  2]
 [82  8 89 97 40 75 41 85 10 26 11 69 13 67 39]
 [94 25 83 39 97 61 29 31 80 15 18 57 22 40 32]
 [73 16 67 28 85  5 91 89 78 22 94 63 25 57 81]
 [89 81 94 56 85 97 82 10 78 15 67 73 59 32 28]
 [52  8 13 55 26  1 82 40 70 58 51  3 69 89 86]
 [86 20  8 52 13 55 82 53  3 85 14 51 75 41 26]
 [75 41 85 57 67 25  2 66 39 97 83 82 89  8 46]
 [40 47 15 23 72 59 66 89 83 12 82 90 71 94 48]
 [66  2 83 48 67 40 38 57 94 89 13 82 41 25 85]
 [ 8 13 40 82 69 26 72 89 53 55 66 51 59 47  3]
 [56 50 84 78 81 63  3 89 85 92 86 82 53 16 59]
 [85 16 75 41 67 89 73 86 82 57  5 97 91 53 25]
 [69 26  8 76 53 40 13  7 41  0 59 58 39 83 82]
 [ 1 39 26 97 40 80 58 69  8 76 46 25 62 82 83]]


In [28]:
import copy
m = 6
xt_j = copy.deepcopy(xt[m, :].reshape(-1, D))
x_j = copy.deepcopy(x[idx[m, :], :])
y_j = copy.deepcopy(y[idx[m, :]])

In [29]:
pred[m], _, tmp_model, _ = JumpGP_LD(x_j, y_j, xt_j, 'CEM', 0)

C:\Users\yxu59\AppData\Local\Temp\ipykernel_5936\1695829151.py:1: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  pred[m], _, tmp_model, _ = JumpGP_LD(x_j, y_j, xt_j, 'CEM', 0)


In [31]:
x_j, y_j, xt_j

(array([[-0.24433199,  0.0504445 ,  0.47479247, -0.63858668,  0.00224485],
        [-0.63895818,  0.06153958,  0.74409429,  0.16581657,  0.44921288],
        [ 0.15139006,  0.14151837,  0.16331329, -0.55879265, -0.19611712],
        [-0.14444252,  0.7385595 ,  0.50661664,  0.00286416, -1.17253819],
        [-0.73882793,  0.69109294, -0.04839477, -0.17719018,  0.224128  ],
        [-0.38198806, -0.52888474,  0.71898291,  0.49619065, -0.88483679],
        [-0.37453679, -0.42441857,  0.34844396,  0.75173337, -0.55746313],
        [ 0.3256974 , -0.56355434,  0.3122346 ,  0.12420065, -0.34879665],
        [-0.09030511,  0.7568936 , -0.11590703, -1.57633405, -0.33979573],
        [-1.35950116,  0.25250721,  0.76261812,  0.89102322,  0.2697348 ],
        [ 0.26191327,  0.49106946,  1.71255363,  0.27519452, -1.31822318],
        [-0.80266502,  0.41105912,  0.55013768,  1.03295145,  0.27265339],
        [-0.80339285, -0.85025974,  0.2154507 ,  0.03102398,  0.64398248],
        [-0.00844478, -0.

In [34]:
print_matlab(x_j, y_j, xt_j)

MATLAB 赋值语句：
x = [-0.24433199068219094 0.05044450202916717 0.4747924686539036 -0.6385866812806132 0.0022448547795987884
-0.6389581841418899 0.06153957963475387 0.7440942895362784 0.1658165739377887 0.44921288073636734
0.1513900616910642 0.14151836586407052 0.163313294981226 -0.5587926523871454 -0.19611712227553962
-0.14444252236206762 0.7385595048024631 0.5066166362836926 0.002864161565029359 -1.1725381898549847
-0.7388279284495607 0.691092936383982 -0.04839477310323366 -0.17719017941379123 0.22412800159796117
-0.3819880637450307 -0.5288847356026766 0.7189829062182337 0.4961906519619119 -0.884836786315632
-0.37453678616638797 -0.4244185729515599 0.34844396461163013 0.7517333684806362 -0.5574631330506424
0.3256973988955894 -0.5635543398183354 0.3122346023241812 0.12420065277083443 -0.34879665263963694
-0.0903051108058979 0.7568935971489539 -0.11590702755029751 -1.5763340528061767 -0.3397957270837957
-1.3595011564839323 0.25250721007135296 0.7626181238543979 0.8910232167571979 0.26973480