In [1]:
from JumpGP_code_py.cov.covSum import covSum
from JumpGP_code_py.cov.covSEard import covSEard
from JumpGP_code_py.cov.covNoise import covNoise
from JumpGP_code_py.lik.loglikelihood import loglikelihood
import numpy as np
from scipy.optimize import minimize
from JumpGP_code_py.local_linearfit import local_linearfit
from JumpGP_code_py.calculate_gx import calculate_gx
from JumpGP_code_py.maximize_PD import maximize_PD
from JumpGP_code_py.JumpGP_LD import JumpGP_LD
from JumpGP_code_py.simulate_case import simulate_case

import matplotlib.pyplot as plt
from sklearn.neighbors import NearestNeighbors
from skimage import measure

import numpy as np
from scipy.optimize import minimize
from scipy.linalg import cholesky
from scipy.stats import norm

from JumpGP_code_py.lik.loglikelihood import loglikelihood
from JumpGP_code_py.calculate_gx import calculate_gx
from JumpGP_code_py.cov.covSum import covSum
from JumpGP_code_py.cov.covSEard import covSEard
from JumpGP_code_py.cov.covNoise import covNoise
from JumpGP_code_py.lik.loglikelihood import loglikelihood

from ActiveJGP import ActiveJGP

import importlib

import numpy as np
import matplotlib.pyplot as plt

from JumpGP_code_py.cov.covSum import covSum
from JumpGP_code_py.cov.covSEard import covSEard
from JumpGP_code_py.cov.covNoise import covNoise
from JumpGP_code_py.lik.loglikelihood import loglikelihood
from JumpGP_code_py.local_linearfit import local_linearfit
from JumpGP_code_py.maximize_PD import maximize_PD
from JumpGP_code_py.calculate_gx import calculate_gx

from run_main_simulation import run_main_simulation

In [2]:
output = True
n = 100  # 行数
D = 5  # 列数
n_test = 1

x = np.random.randn(n, D)  # 生成 n x D 的随机矩阵
x0 = np.random.randn(n_test, D)

# 随机生成 Target Outputs (y)
y = np.random.randn(n, 1)  # 生成 n 行 1 列的随机列向量

# 随机生成 logtheta
logtheta = np.random.randn(D+2)  # 生成 D+1 维的随机向量
loglike = loglikelihood(logtheta, covSum, [covSEard, covNoise], x, y)
print(f"***loglike:{loglike}")

# 转换为 MATLAB 赋值语句
x_matlab = '\n'.join([' '.join(map(str, row)) for row in x])
y_matlab = '\n'.join(map(str, y.flatten()))
x_test_matlab = '\n'.join([' '.join(map(str, row)) for row in x0])
logtheta_matlab = ';\n'.join(map(str, logtheta))

if output is True:
    print("MATLAB 赋值语句：")
    print(f"x = [{x_matlab}];")
    print(f"y = [{y_matlab}];")
    print(f"x0 = [{x_test_matlab}];")
    print(f"logtheta = [{logtheta_matlab}];")
    print(f"loglike = loglikelihood(logtheta, cv,x,y);")


***loglike:175.2762701337295
MATLAB 赋值语句：
x = [-1.5832153459408942 -0.47674167883984564 0.42245608902726645 -1.1881556402340285 0.14573377319732464
-0.24999767184035498 -2.8379093242844116 -0.4886673065640865 2.062035701132877 -1.9005980911659668
0.773809819543915 -1.0719116594465832 1.0026668172970739 1.1275152145169351 -0.1288912014996591
-0.9830398113148289 -0.09880206489460823 0.5447555531737913 0.23152645715343959 -1.6306490419238973
-0.35207617544844066 -2.2898758487379984 1.4824539463376831 -0.2682824213350567 1.171553767225636
0.20416222284792357 -1.5995823535431488 -0.4423068464380584 1.810244640383142 0.8833164224255116
0.8867451970900467 -1.5123805612510361 0.4875994073144854 -0.10165325389114874 -0.6522892063033799
1.4194684668308315 -0.5927217666593521 1.4824964817247521 -0.30459853849418317 1.1544108306689507
0.5873153835536888 1.546471864556867 0.009556496319274688 1.7219232269390694 0.033200094123510736
0.3162756553251532 1.3681013005144014 -0.7884005410843705 -1.479507

In [3]:
from calcALC import calcALC

In [4]:
cv = [covSum, [covSEard, covNoise]]
ALC = calcALC(x, x0, cv, logtheta)

In [6]:
ALC.shape

(20,)

In [7]:
ALC

array([8.63877943, 8.88542959, 8.9401153 , 8.95693029, 8.95254085,
       8.86674607, 8.94086169, 8.95772913, 9.03390805, 8.4143066 ,
       8.95843399, 8.95854438, 8.95849575, 7.8262458 , 8.84110481,
       8.9559188 , 8.95854427, 8.95854435, 8.95854441, 8.49305487])

In [45]:
import JumpGP_code_py.JumpGP_LD
import importlib
importlib.reload(JumpGP_code_py.JumpGP_LD)
from JumpGP_code_py.JumpGP_LD import JumpGP_LD

In [52]:
x0

array([[ 0.52348186, -1.14943194]])

In [3]:
mu_t, sig2_t, model, h = JumpGP_LD(x,y,x0.reshape(1,-1),'CEM',0)

In [4]:
x.shape,y.shape,x0[0,:].shape

((100, 5), (100, 1), (5,))

In [5]:
from calculate_bias_and_variance import calculate_bias_and_variance

In [6]:
mu_t, sig2_t, model

(array([[-0.27343919]]),
 array([[0.59746111]]),
 {'x': array([[-1.58321535e+00, -4.76741679e-01,  4.22456089e-01,
          -1.18815564e+00,  1.45733773e-01],
         [-2.49997672e-01, -2.83790932e+00, -4.88667307e-01,
           2.06203570e+00, -1.90059809e+00],
         [ 7.73809820e-01, -1.07191166e+00,  1.00266682e+00,
           1.12751521e+00, -1.28891201e-01],
         [-9.83039811e-01, -9.88020649e-02,  5.44755553e-01,
           2.31526457e-01, -1.63064904e+00],
         [-3.52076175e-01, -2.28987585e+00,  1.48245395e+00,
          -2.68282421e-01,  1.17155377e+00],
         [ 2.04162223e-01, -1.59958235e+00, -4.42306846e-01,
           1.81024464e+00,  8.83316422e-01],
         [ 8.86745197e-01, -1.51238056e+00,  4.87599407e-01,
          -1.01653254e-01, -6.52289206e-01],
         [ 1.41946847e+00, -5.92721767e-01,  1.48249648e+00,
          -3.04598538e-01,  1.15441083e+00],
         [ 5.87315384e-01,  1.54647186e+00,  9.55649632e-03,
           1.72192323e+00,  3.3200094

In [62]:
x0

array([[-2.55528124,  0.13171366]])

In [16]:
xt = x0[0,:].reshape(1,-1)
r = model['r']
# x = model['x']
r1 = r.flatten()
K = covSum([covSEard, covNoise], model['logtheta'], x[r1,:])
Ktt, Kt = covSum([covSEard, covNoise], model['logtheta'], x[r1,:], xt)

In [17]:
Ktt

array([[0.5292635]])

In [20]:
K += 1e-8 * np.eye(K.shape[0])
L = cholesky(K, lower=True)
Ly = np.linalg.solve(L, y[r1] - model['ms'])
LK = np.linalg.solve(L, Kt)

In [21]:
np.sum(LK.T**2, axis=1)

array([0.46496196])

In [7]:
xt = x0
bias2, var, bias, parts = calculate_bias_and_variance(model, xt)

In [8]:
bias2, var, bias, parts

(0.0009194441608101933,
 0.5974611078447742,
 -0.030322337654115544,
 array([[ 0.04851838],
        [-0.        ],
        [-0.03390739],
        [ 0.00922693],
        [ 0.41424616]]))

In [27]:
import numpy as np
import matplotlib.pyplot as plt

from JumpGP_code_py.cov.covSum import covSum
from JumpGP_code_py.cov.covSEard import covSEard
from JumpGP_code_py.cov.covNoise import covNoise
from JumpGP_code_py.lik.loglikelihood import loglikelihood
from JumpGP_code_py.local_linearfit import local_linearfit
from JumpGP_code_py.maximize_PD import maximize_PD
from JumpGP_code_py.calculate_gx import calculate_gx

args = []
cv = [covSum, [covSEard, covNoise]]
d = x.shape[1]  # Get the number of features (columns)
px = x
pxt = xt

# Initial estimation of the boundary B(x)
logtheta = np.zeros(d + 2)
logtheta[d + 2 - 1] = -1.15
if len(args)>0:
    logtheta = args[0]
w, _ = local_linearfit(x, y, xt)
nw = np.linalg.norm(w)
w = w / nw

# Fine-tune the intercept term
try:
    # print(w)
    b = np.arange(-1 + w[0].item(), 1 + w[0].item() , 0.01)
except:
    print(f"x is {x}, y is {y}, xt is {xt}")
    print(f"Error with JumpGP_LD, w is {w}")
fd = []
for bi in b:
    w_d = w.copy()
    w_d[0] = bi
    gx, _ = calculate_gx(px, w_d)
    r = gx >= 0
    var_r = np.var(y[r], ddof=1) if np.sum(r) > 1 else 0
    var_not_r = np.var(y[~r], ddof=1) if np.sum(~r) > 1 else 0
    fd.append(np.mean(r) * var_r + np.mean(~r) * var_not_r)

try:
    k = np.nanargmin(fd)
except:
    print("JumpGP_LD, fd is all nan")
    k = 0
w[0] = b[k]
w = nw * w

In [31]:
logtheta

array([ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  , -1.15])

In [32]:
mu_t, sig2_t, model, h = JumpGP_LD(x, y, xt, mode, bVerbose=0, logtheta, cv)

SyntaxError: positional argument follows keyword argument (1232127694.py, line 1)

In [33]:
model = maximize_PD(x, y, xt, px, pxt, w, logtheta, cv, bVerbose=False)

In [34]:
model

{'x': array([[-1.24618770e+00,  5.10990410e-01,  4.64771539e-03,
         -1.48164229e-01, -8.85700766e-03],
        [-6.37352769e-01, -4.99420526e-01,  1.95467503e+00,
          2.40034528e+00,  2.55327982e+00],
        [ 8.74333205e-01,  2.29313053e+00, -1.04539793e+00,
          2.22347564e+00, -1.57023275e+00],
        [ 1.97365049e+00,  1.95778407e-01, -5.49611409e-02,
         -2.15821660e-01,  4.85287427e-01],
        [-2.05567445e+00, -2.95543901e-01,  2.93003205e-01,
          6.14556063e-01,  6.97361894e-01],
        [-1.62074198e+00,  6.04143872e-01, -3.44978512e-01,
          1.13103553e+00, -2.17236610e-01],
        [-1.91139502e+00, -1.22458213e+00, -1.47690533e+00,
          9.47387207e-01, -1.18854441e-01],
        [-2.84174301e-01,  1.61298791e-01,  9.68956179e-01,
         -2.87590607e-01,  6.47320882e-01],
        [ 9.32522840e-01,  3.33700981e-01, -1.14119209e+00,
          9.87069767e-01,  1.03631271e+00],
        [ 1.80373188e+00, -2.69255483e-01, -5.55574269e-01,

In [36]:
model['w']


array([-0.57884606,  0.1708835 ,  0.30075888,  0.3606607 , -0.64389356,
        0.02459901])

In [37]:
model

{'x': array([[-1.24618770e+00,  5.10990410e-01,  4.64771539e-03,
         -1.48164229e-01, -8.85700766e-03],
        [-6.37352769e-01, -4.99420526e-01,  1.95467503e+00,
          2.40034528e+00,  2.55327982e+00],
        [ 8.74333205e-01,  2.29313053e+00, -1.04539793e+00,
          2.22347564e+00, -1.57023275e+00],
        [ 1.97365049e+00,  1.95778407e-01, -5.49611409e-02,
         -2.15821660e-01,  4.85287427e-01],
        [-2.05567445e+00, -2.95543901e-01,  2.93003205e-01,
          6.14556063e-01,  6.97361894e-01],
        [-1.62074198e+00,  6.04143872e-01, -3.44978512e-01,
          1.13103553e+00, -2.17236610e-01],
        [-1.91139502e+00, -1.22458213e+00, -1.47690533e+00,
          9.47387207e-01, -1.18854441e-01],
        [-2.84174301e-01,  1.61298791e-01,  9.68956179e-01,
         -2.87590607e-01,  6.47320882e-01],
        [ 9.32522840e-01,  3.33700981e-01, -1.14119209e+00,
          9.87069767e-01,  1.03631271e+00],
        [ 1.80373188e+00, -2.69255483e-01, -5.55574269e-01,